#!/usr/bin/env python3

import argparse

import pandas as pd
import matplotlib.pyplot as plt


def build_active_connection_series(df: pd.DataFrame, duration: float):
    """
    Build a step-series representing the number of active connections over time.

    A connection becomes active at start_time.
    A connection becomes inactive at close_time, if close_time is present.
    If close_time is missing, the connection is considered active until the end
    of the experiment.
    """

    events = []

    for _, row in df.iterrows():
        start_time = row["start_time"]
        close_time = row["close_time"]

        if pd.notna(start_time):
            events.append((float(start_time), +1))

        if pd.notna(close_time):
            events.append((float(close_time), -1))

    # Sort by time. If start and close happen at exactly the same time,
    # process closures first to avoid artificial spikes.
    events.sort(key=lambda x: (x[0], x[1]))

    times = [0.0]
    active_counts = [0]

    active = 0

    for time, delta in events:
        # Horizontal segment until this event.
        times.append(time)
        active_counts.append(active)

        # Apply event.
        active += delta

        # Vertical jump at this event.
        times.append(time)
        active_counts.append(active)

    # Extend to the end of the experiment.
    times.append(duration)
    active_counts.append(active)

    return times, active_counts


def plot_active_connections(
    df: pd.DataFrame,
    output_path: str,
    duration: float,
    expected_connections: int,
    title: str,
):
    times, active_counts = build_active_connection_series(df, duration)

    max_active = max(active_counts) if active_counts else 0
    final_active = active_counts[-1] if active_counts else 0

    plt.figure(figsize=(14, 6))

    plt.step(
        times,
        active_counts,
        where="post",
        linewidth=1.8,
        label="Active successful connections",
    )

    # Reference line for expected attack connections.
    plt.axhline(
        y=expected_connections,
        linestyle="--",
        linewidth=1.0,
        label=f"Expected connections: {expected_connections}",
    )

    plt.xlabel("Time since beginning of capture [s]")
    plt.ylabel("Number of active connections")
    plt.xlim(0, duration)

    ymax = max(expected_connections, max_active)
    plt.ylim(0, ymax * 1.05 if ymax > 0 else 1)

    plt.title(
        f"{title} "
        f"(max={max_active}, final={final_active})"
    )

    plt.legend(loc="best")
    plt.grid(True, linewidth=0.3, alpha=0.5)
    plt.tight_layout()

    plt.savefig(output_path, dpi=600)
    plt.close()

    return max_active, final_active


def main():
    parser = argparse.ArgumentParser(
        description="Plot active RTSP connections over time from connection CSV."
    )

    parser.add_argument(
        "csv",
        help="CSV generated by plot_rtsp_connections.py",
    )

    parser.add_argument(
        "--duration",
        type=float,
        default=5200,
        help="Experiment duration shown on x-axis. Default: 5200",
    )

    parser.add_argument(
        "--expected-connections",
        type=int,
        default=1016,
        help="Expected number of attack connections. Default: 1016",
    )

    parser.add_argument(
        "--title",
        default="Active RTSP connections over time",
        help="Plot title. Default: Active RTSP connections over time",
    )

    parser.add_argument(
        "--out",
        default="active_connections_over_time.png",
        help="Output plot filename",
    )

    args = parser.parse_args()

    df = pd.read_csv(args.csv)

    required_columns = {"connection_id", "start_time", "close_time"}
    missing_columns = required_columns - set(df.columns)

    if missing_columns:
        raise ValueError(
            f"Missing required columns in CSV: {', '.join(sorted(missing_columns))}"
        )

    total_successful = len(df)
    total_closed = int(df["close_time"].notna().sum())
    total_still_open = total_successful - total_closed

    max_active, final_active = plot_active_connections(
        df=df,
        output_path=args.out,
        duration=args.duration,
        expected_connections=args.expected_connections,
        title=args.title,
    )

    print(f"Total successful connections: {total_successful}")
    print(f"Total closed connections: {total_closed}")
    print(f"Total still open at end: {total_still_open}")
    print(f"Maximum active connections at the same time: {max_active}")
    print(f"Final active connections: {final_active}")
    print(f"Plot written to: {args.out}")


if __name__ == "__main__":
    main()